services:
  backend:
    build: back-end/
    ports:
      - "8080:8080"
    env_file:
      - back-end/.env
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  frontend:
    build:
      context: front-end/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - /app/node_modules
    depends_on:
       - redis

volumes:
  node_modules:

networks:
  default:
