services:
  backend:
    build: back-end/
    ports:
      - "8080:8080"
    env_file:
      - back-end/.env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d movies -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
  frontend:
    build:
      context: front-end/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5173:5173
    volumes:
      - /app/node_modules
    depends_on:
       - postgres

volumes:
  node_modules:
  postgres_data:

networks:
  default:
